#!/bin/bash

mkdir include lib doc src data &&
mkdir src/main && touch src/main/main.cpp &&
mkdir src/class &&

if [ "$1" !=  '' ]
then
echo "
#include \"../../include/$1.class.hpp\"


$1::$1(){}
$1::$1(const $1& src){
	*this = src;
}
$1::~$1(){}

$1& $1::operator=($1 const & e){
	$1::<CHANGE_FUNC_NAME>(e.<CHANGE_FUNC_NAME>());
	return *this;
}

" >> "src/class/$1.class.cpp" &&

echo "
#pragma once

class $1 {
	public:

		$1();
		$1(const $1& src);
		~$1();

		$1& operator=($1 const & e);

	private:

};" >> "include/$1.class.hpp"
fi
if [ "$2" != '' ]
then
echo "
#include \"../../include/$2.class.hpp\"


$2::$2(){}
$2::$2(const $2& src){
	*this = src;
}
$2::~$2(){}

$2& $2::operator=($2 const & e){
	$2::<CHANGE_FUNC_NAME>(e.<CHANGE_FUNC_NAME>());
	return *this;
}

" >> "src/class/$2.class.cpp" &&
echo "
#pragma once

class $2 {
	public:

		$2();
		$2(const $2& src);
		~$2();

		$2& operator=($2 const & e);

	private:

};" >> "include/$2.class.hpp"
fi

if [ "$3" != '' ]
then
echo "
#include \"../../include/$3.class.hpp\"


$3::$3(){}
$3::$3(const $3& src){
	*this = src;
}
$3::~$3(){}

$3& $3::operator=($3 const & e){
	$3::<CHANGE_FUNC_NAME>(e.<CHANGE_FUNC_NAME>());
	return *this;
}

" >> "src/class/$3.class.cpp" &&
echo "
#pragma once

class $3 {
	public:

		$3();
		$3(const $3& src);
		~$3();

		$3& operator=($3 const & e);

	private:

};" >> "include/$3.class.hpp"
fi

if [ "$4" != '' ]
then
echo "
#include \"../../include/$4.class.hpp\"


$4::$4(){}
$4::$4(const $4& src){
	*this = src;
}
$4::~$4(){}

$4& $4::operator=($4 const & e){
	$4::<CHANGE_FUNC_NAME>(e.<CHANGE_FUNC_NAME>());
	return *this;
}

" >> "src/class/$4.class.cpp" &&
echo "
#pragma once

class $4 {
	public:

		$4();
		$a(const $4&src );
		~$4();

		$4& operator=($4 const & e);

	private:

};" >> "include/$4.class.hpp"
fi

cp ~/42/42MakefileTemplate.cpp/Makefile ./Makefile &&
make setup &&
find "." -name .git -prune -o -type d -empty -exec  touch {}/.gitignore \;
